# Generated by Django 4.1 on 2022-09-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0004_remove_order_quantity_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
