# Generated by Django 4.1 on 2022-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0006_orderproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ManyToManyField(to='Portal.product'),
        ),
    ]
